### PR TITLE
Update zero_cnt_of_factorial.py

### PR DESCRIPTION
**Pull request by ghost**
Made the function short and correct.

### CODE REVIEW

**Comment by vvs14** [comment]
My code is correct. You can verify from web. One of the links is : [](http://www.purplemath.com/modules/factzero.htm)

**Comment by ghost** [comment]
My code is correct. You can verify from web.
can you please check your algorithm's correctness?

**Comment by smilejay** [comment]
thank you very much. You're right. I'll correct my code.

**Comment by ghost** [comment]
You are welcome.

**Pull request merged**
